name: build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    
    - name: Install Ruby (3.0)
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 3.0.3
        bundler-cache: true
        
    - name: Setup CodeClimate test-reporter
      run: |
        curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        chmod +x ./cc-test-reporter
        ./cc-test-reporter before-build
        
    - name: Install bundler and dependencies
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        
    - name: Setup PostgreSQL
      run: |
        sudo apt-get install postgresql libpq-dev
        sudo service postgresql start
        sudo -u postgres createuser --superuser "$USER"
        
    - name: Setup database
      run: |
        bundle exec rake db:create db:migrate
        
    - name: run RSpec tests and capture coverage
      run: |
        bundle exec rspec
        
    - name: run Cucumber tests and capture coverage
      run: |
        bundle exec cucumber

    - name: Publish code coverage
      run: |
        ./cc-test-reporter after-build -r 1d6761e54cf0ce3a62d015dbdef28a91f8440d1ccaa4f86a5dd9ecf9ff58cbf4
