name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Ruby (3.0)
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 3.0.3
    - name: Build and test with RSpec
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rspec
